name: Pull Request

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout branch
      uses: actions/checkout@v3

    - name: Lint
      uses: golangci/golangci-lint-action@v3.3.1

    - name: Test
      run: make test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3

    - name: Build
      run: make build
